name: Publish
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  lint:
    name: Run Golang-CI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Run Golang-CI Lint
        uses: golangci/golangci-lint-action@v9

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Test
        run: >
          go tool gotestsum
          --jsonfile gotestsum.json
          --packages="./..."
          --format github-actions
          --
          -coverpkg=./...
          -coverprofile=coverage.out

      - name: Convert report into ctrf
        if: ${{ !cancelled() }}
        run: go tool go-ctrf-json-reporter -output report.json < gotestsum.json

      - name: Publish Test Report to PR
        uses: ctrf-io/github-test-reporter@v1.0.27
        if: ${{ !cancelled() && github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Test Results
          report-path: "report.json"
          pull-request: true
          pull-request-report: true
          comment-tag: ${{ github.workflow }}-${{ github.job }}
          overwrite-comment: true

      - name: Publish Test Report to Summary
        uses: ctrf-io/github-test-reporter@v1.0.27
        if: ${{ !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Test Results
          report-path: "report.json"
          summary: true
          summary-report: true
          failed-report: true

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: coverage.out
          report: "true"
          chart: "true"
          amend: "true"

  tag:
    name: Increment Tag
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    outputs:
      version: ${{ steps.version.outputs.version }}
      v-version: ${{ steps.version.outputs.v-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: calver
          increment: patch
          tag_prefix: v

      - name: Create tag
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.v-version }}',
              sha: context.sha
            })

  release:
    name: GoReleaser Release
    needs:
      - tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAPS_KEY: ${{ secrets.TAPS_KEY }}
          GORELEASER_CURRENT_TAG: ${{ needs.tag.outputs.v-version }}
